#!/usr/bin/env bash

set -euxo pipefail

# install homebrew
if ! command -v brew; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# check homebrew
brew --version

# install luckycoin
if ! command -v luckycoind; then
  brew install luckycoin
fi

# check luckycoind
luckycoind --version

# write config
if [[ ! -f ~/Library/Application\ Support/Luckycoin/luckycoin.conf ]]; then
  printf 'txindex=1\nsignet=1\n' > ~/Library/Application\ Support/Luckycoin/luckycoin.conf
fi

# start luckycoind
if ! luckycoin-cli getblockchaininfo; then
  brew services start luckycoin
fi

# check luckycoind
luckycoin-cli getblockchaininfo | grep signet

# install ord
if ! command -v ord; then
  curl --proto '=https' --tlsv1.2 -fsLS https://raw.githubusercontent.com/toregua/ord-luckycoin/master/install.sh?token=GHSAT0AAAAAAB657S54D565E7TB4B3NBCE4Y736PRQ | bash -s
fi

# check ord
ord --version
